# Generated by Django 5.0.2 on 2024-03-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_todoapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoapp',
            old_name='uid',
            new_name='user',
        ),
    ]
